import { Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import WorkOutProvider from "./context/workoutcontext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkOutProvider>
          <Header />
          <main className="py-12">
            {children}
            <ToastContainer />
          </main>
          <Footer />
        </WorkOutProvider>
      </body>

    </html>
  );
}
